app/about/routes.py
from flask import render_template, Blueprint
about = Blueprint('about', __name__)

@about.route('/about')
def page():
  return render_template('about.html')

app/calculator/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, flash, jsonify
from app.models import Transport
from app import db
from datetime import timedelta, datetime
from flask_login import login_required, current_user
from app.calculator.forms import Form
import json

calculator=Blueprint('calculator',__name__)

#Emissions factor per transport in kg per passemger km
#Data from: http://efdb.apps.eea.europa.eu/?source=%7B%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%2C%22display_type%22%3A%22tabular%22%7D
efco2={'Bus':{'Diesel':0.03,'CNG':0.0285, 'No Fossil Fuel':0.013},
    'Car':{'Petrol':0.180,'Diesel':0.160, 'Hybrid (gasoline)': 0.100, 'CNG': 0.130, 'No Fossil Fuel':0.026},
    'Train': {'Diesel': 0.027, 'Biodiesel': 0.014, 'No Fossil Fuel': 0.013}, ##ADD BIODIESEL
    'Plane':{'Petrol':0.300},
    'Ferry':{'Diesel':0.019, 'CNG': 0.01425},
    'Motorbike':{'Petrol':0.200},
    'Scooter':{'Petrol': 0.100,'No Fossil Fuel':0},
    'Bicycle':{'No Fossil Fuel':0},
    'Walk':{'No Fossil Fuel':0}}


#Calculator, main page
@calculator.route('/calculator', methods=['GET','POST'])
@login_required
def page():
    form = Form()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = form.method.data
        passengers = form.passengers.data
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * (efco2[transport][fuel]/passengers)

        co2 = float("{:.2f}".format(co2))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('calculator.your_data'))
    return render_template('calculator/calculator.html', title='New entry', form=form)

@calculator.route('/get-items')
def get_items():
    method = request.args.get('method')
    items_dict = {
        'Bus': ['Diesel', 'CNG', 'No Fossil Fuel'],
        'Car': ['Petrol', 'Diesel', 'Hybrid (gasoline)', 'CNG', 'No Fossil Fuel'],
        'Train': ['Diesel', 'Biodiesel', 'No Fossil Fuel'],
        'Plane': ['Petrol'],
        'Ferry': ['Diesel', 'CNG'],
        'Motorbike': ['Petrol'],
        'Scooter': ['Petrol', 'No Fossil Fuel'],
        'Bicycle': ['No Fossil Fuel'],
        'Walk': ['No Fossil Fuel']
    }
    items = items_dict.get(method, [])
    return jsonify({'items': items})


#Your data
@calculator.route('/calculator/your_data')
@login_required
def your_data():
    #Table
    entries = Transport.query.filter_by(author=current_user). \
        filter(Transport.date> (datetime.now() - timedelta(days=30))).\
        order_by(Transport.date.desc()).order_by(Transport.transport.asc()).all()

#Emissions by category
    emissions_by_transport = db.session.query(db.func.sum(Transport.co2), Transport.transport). \
        filter(Transport.date > (datetime.now() - timedelta(days=30))).filter_by(author=current_user). \
        group_by(Transport.transport).order_by(Transport.transport.asc()).all()
    emission_transport = [0, 0, 0, 0, 0, 0, 0, 0, 0]
    first_tuple_elements = []
    second_tuple_elements = []
    for a_tuple in emissions_by_transport:
        first_tuple_elements.append(a_tuple[0])
        second_tuple_elements.append(a_tuple[1])

    if 'Bus' in second_tuple_elements:
        index_bus = second_tuple_elements.index('Bus')
        emission_transport[1]=first_tuple_elements[index_bus]
    else:
        emission_transport[1]

    if 'Car' in second_tuple_elements:
        index_car = second_tuple_elements.index('Car')
        emission_transport[2]=first_tuple_elements[index_car]
    else:
        emission_transport[2]

    if 'Ferry' in second_tuple_elements:
        index_ferry = second_tuple_elements.index('Ferry')
        emission_transport[3]=first_tuple_elements[index_ferry]
    else:
        emission_transport[3]

    if 'Motorbike' in second_tuple_elements:
        index_motorbike = second_tuple_elements.index('Motorbike')
        emission_transport[4]=first_tuple_elements[index_motorbike]
    else:
        emission_transport[4]

    if 'Plane' in second_tuple_elements:
        index_plane = second_tuple_elements.index('Plane')
        emission_transport[5]=first_tuple_elements[index_plane]
    else:
        emission_transport[5]
    
    if 'Scooter' in second_tuple_elements:
        index_scooter = second_tuple_elements.index('Scooter')
        emission_transport[6]=first_tuple_elements[index_scooter]
    else:
        emission_transport[6]

    if 'Train' in second_tuple_elements:
        index_train = second_tuple_elements.index('Train')
        emission_transport[7]=first_tuple_elements[index_train]
    else:
        emission_transport[7]

    #Kilometers by category
    kms_by_transport = db.session.query(db.func.sum(Transport.kms), Transport.transport). \
        filter(Transport.date > (datetime.now() - timedelta(days=30))).filter_by(author=current_user). \
        group_by(Transport.transport).order_by(Transport.transport.asc()).all()
    kms_transport = [0, 0, 0, 0, 0, 0, 0, 0, 0]
    first_tuple_elements = []
    second_tuple_elements = []
    for a_tuple in kms_by_transport:
        first_tuple_elements.append(a_tuple[0])
        second_tuple_elements.append(a_tuple[1])

    if 'Bicycle' in second_tuple_elements:
        index_bicycle = second_tuple_elements.index('Bicycle')
        kms_transport[0]=first_tuple_elements[index_bicycle]
    else:
        kms_transport[0] 

    if 'Bus' in second_tuple_elements:
        index_bus = second_tuple_elements.index('Bus')
        kms_transport[1]=first_tuple_elements[index_bus]
    else:
        kms_transport[1]

    if 'Car' in second_tuple_elements:
        index_car = second_tuple_elements.index('Car')
        kms_transport[2]=first_tuple_elements[index_car]
    else:
        kms_transport[2]

    if 'Ferry' in second_tuple_elements:
        index_ferry = second_tuple_elements.index('Ferry')
        kms_transport[3]=first_tuple_elements[index_ferry]
    else:
        kms_transport[3]

    if 'Motorbike' in second_tuple_elements:
        index_motorbike = second_tuple_elements.index('Motorbike')
        kms_transport[4]=first_tuple_elements[index_motorbike]
    else:
        kms_transport[4]

    if 'Plane' in second_tuple_elements:
        index_plane = second_tuple_elements.index('Plane')
        kms_transport[5]=first_tuple_elements[index_plane]
    else:
        kms_transport[5]

    if 'Scooter' in second_tuple_elements:
        index_scooter = second_tuple_elements.index('Scooter')
        kms_transport[6]=first_tuple_elements[index_scooter]
    else:
        kms_transport[6]   

    if 'Train' in second_tuple_elements:
        index_train = second_tuple_elements.index('Train')
        kms_transport[7]=first_tuple_elements[index_train]
    else:
        kms_transport[7]   

    if 'Walk' in second_tuple_elements:
        index_walk = second_tuple_elements.index('Walk')
        kms_transport[8]=first_tuple_elements[index_walk]
    else:
        kms_transport[8]    

    #Emissions by date (individual)
    emissions_by_date = db.session.query(db.func.sum(Transport.co2), Transport.date). \
        filter(Transport.date > (datetime.now() - timedelta(days=30))).filter_by(author=current_user). \
        group_by(Transport.date).order_by(Transport.date.asc()).all()
    over_time_emissions = []
    dates_label = []
    for total, date in emissions_by_date:
        dates_label.append(date.strftime("%m-%d-%y"))
        over_time_emissions.append(total)    

    #Kms by date (individual)
    kms_by_date = db.session.query(db.func.sum(Transport.kms), Transport.date). \
        filter(Transport.date > (datetime.now() - timedelta(days=30))).filter_by(author=current_user). \
        group_by(Transport.date).order_by(Transport.date.asc()).all()
    over_time_kms = []
    dates_label = []
    for total, date in kms_by_date:
        dates_label.append(date.strftime("%m-%d-%y"))
        over_time_kms.append(total)      


    return render_template('calculator/your_data.html', title='Your Data', entries=entries,
        emissions_by_transport_python_dic=emissions_by_transport,     
        emission_transport_python_list=emission_transport,             
        emissions_by_transport=json.dumps(emission_transport),
        kms_by_transport=json.dumps(kms_transport),
        over_time_emissions=json.dumps(over_time_emissions),
        over_time_kms=json.dumps(over_time_kms),
        dates_label=json.dumps(dates_label))
    

#Delete emission
@calculator.route('/calculator/delete-emission/<int:entry_id>')
def delete_emission(entry_id):
    entry = Transport.query.get_or_404(int(entry_id))
    db.session.delete(entry)
    db.session.commit()
    flash("Entry deleted", "success")
    return redirect(url_for('calculator.your_data'))
    
  

app/home/routes.py
from flask import render_template, Blueprint
from app.models import User, Transport

home=Blueprint('home',__name__)

@home.route('/')
def page():
  return render_template('home.html')

app/methodology/routes.py
from flask import render_template, Blueprint, send_file
methodology = Blueprint('methodology', __name__)

@methodology.route('/methodology')
def page():
  return render_template('methodology.html')

@methodology.route('/downloadPaper')
def download ():
    path = "./static/downloadable/Carbon-App-Paper-Group-3-2025.pdf"
    return send_file(path, as_attachment=True)

app/users/routes.py
from flask import render_template, Blueprint, redirect, flash, url_for, request
from app.users.forms import RegistrationForm, LoginForm
from app.models import User
from app import db, bcrypt
from flask_login import login_user, current_user, logout_user

users=Blueprint('users',__name__)

@users.route('/register', methods=['GET','POST'])
def register():
  form = RegistrationForm()
  if current_user.is_authenticated:
        return redirect(url_for('home.page'))
  if form.validate_on_submit():
      user_hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
      user = User(username=form.username.data, email=form.email.data, password=user_hashed_password)
      db.session.add(user)
      db.session.commit()
      flash('Your account has been created! You can now login!', 'success')
      return redirect(url_for('users.login'))
  return render_template('users/register.html', title='register', form=form)

@users.route('/login', methods=['GET','POST'])
def login():
  form = LoginForm()
  if current_user.is_authenticated:
        return redirect(url_for('home.page'))
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
        login_user(user, remember=form.remember.data)
        next_page = request.args.get('next')
        return redirect(next_page) if next_page else redirect(url_for('home.page'))
    else:
        flash('Login unsuccessful. Please check your email and password!', 'danger') 
  return render_template('users/login.html', title='login', form=form)

@users.route('/logout')
def logout():    
    logout_user()
    return redirect(url_for('home.page'))




app/templates/about.html
{% extends "layout.html" %}
{% block content %}

<head>
  <link rel="stylesheet" href="{{url_for('static', filename='./styles/about.css')}}">
</head>

<div class="container">
  <h1>- About Us -</h1>
  <br>
  <h5>We are a group of students that are interested in transport carbon emission problematics!</h5>
  <h5>Meet our team:</h5>
  <br>
  <div class="row row-cols-1 row-cols-md-3 g-4 mb-4">
    <div class="col">
      <div class="card h-100">
        <div class="ratio ratio-1x1 rounded-circle overflow-hidden">
          <img src="{{url_for('static', filename='./images/hugo.jpeg')}}" class="card-img-top img-cover" alt="dev2">
        </div>
        <div class="card-body">
          <h5 class="card-title">Hugo Toorenaar</h5>
          <p class="card-text">Bonjour, I’m Hugo and I come from Toulouse, France. I am an Erasmus student at NHH since August. In my free time, I enjoy running.</p>

        </div>
        <div class="card-footer">
          
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <div class="ratio ratio-1x1 rounded-circle overflow-hidden">
          <img src="{{url_for('static', filename='./images/Uten navn.jpg')}}" class="card-img-top img-cover" alt="dev2">
        </div>
        <div class="card-body">
          <h5 class="card-title">Marte Elisabeth Kvingedal</h5>
          <p class="card-text">Hi, my name is Marte. I am a 20-year-old student from Norway currently taking a bachelor in Economics and Business Administration 
            at the Norwegian School of Economics in Bergen.</p>

        </div>
        <div class="card-footer">
          <a href="https://www.linkedin.com/in/marte-kvingedal-858671300/" class="btn linkedin-btn">LinkedIn</a>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <div class="ratio ratio-1x1 rounded-circle overflow-hidden">
          <img src="{{url_for('static', filename='./images/Jo.jpg')}}" class="card-img-top img-cover" alt="dev2">
        </div>
        <div class="card-body">
          <h5 class="card-title">Jo Brun Larsen</h5>
          <p class="card-text">Hello! My name is Jo. I am a 19-year-old student from Norway currently taking a bachelor in Economics and Business Administration
          at the Norwegian School of Economics in Bergen.</p>

        </div>
        <div class="card-footer">
          
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <div class="ratio ratio-1x1 rounded-circle overflow-hidden">
          <img src="{{url_for('static', filename='./images/kentin.jpeg')}}" class="card-img-top img-cover" alt="dev2">
        </div>
        <div class="card-body">
          <h5 class="card-title">Kentin Le Men</h5>
          <p class="card-text">Hi, I'm Kentin LE MEN, I'm 21 and I'm a student from Montpellier in France. I'm actually in exchange at NHH for the semester.</p>

        </div>
        <div class="card-footer">
          
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <div class="ratio ratio-1x1 rounded-circle overflow-hidden">
          <img src="{{url_for('static', filename='./images/matteo.jpg')}}" class="card-img-top img-cover" alt="dev2">
        </div>
        <div class="card-body">
          <h5 class="card-title">Matteo Wolf</h5>
          <p class="card-text">Hello, my name is Matteo WOLF. I am 21 years old and I come from France. 
            I am currently pursuing a Master 1 at Montpellier Business School, a business school in France. 
            At the moment, I am on an exchange program at NHH in Bergen, Norway. 
            I am also passionate about sports, whether it’s football, weight training, hiking, or running.</p>

        </div>
        <div class="card-footer">
          <a href="https://www.linkedin.com/in/matteo-wolf-968482166/" class="btn linkedin-btn">LinkedIn</a>
          <a href="https://github.com/Matteo-Wolf" class="btn github-btn">GitHub</a>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <div class="ratio ratio-1x1 rounded-circle overflow-hidden">
          <img src="{{url_for('static', filename='./images/vojtech.JPG')}}" class="card-img-top img-cover" alt="dev1">
        </div>
        <div class="card-body">
          <h5 class="card-title">Vojtěch Dejnožka</h5>
          <p class="card-text">Hi, I'm Vojtěch. I'm a 21-year-old student from Czechia. I'm studying Data Science at the
            Prague University of Economics and Business, and I'm currently on an exchange at the NHH. In my free time, I
            enjoy hiking, which I combine with my love for traveling, orienteering, climbing, and board games.</p>
        </div>
        <div class="card-footer">
          <a href="https://www.linkedin.com/in/vojtechdejnozka/" class="btn linkedin-btn">LinkedIn</a>
          <a href="https://github.com/VojtechDejnozka" class="btn github-btn">GitHub</a>
        </div>
      </div>
    </div>
    <div class="col">

    </div>
    <div class="col">
      <div class="card h-100">
        <div class="ratio ratio-1x1 rounded-circle overflow-hidden">
          <img src="{{url_for('static', filename='./images/Janis_Reboul.jpg')}}" class="card-img-top img-cover" alt="dev2">
        </div>
        <div class="card-body">
          <h5 class="card-title">Janis Reboul</h5>
          <p class="card-text">Hi, I'm Janis. I'm currently a Skema BS first year master student in Asset Management.
            By raising awareness through this app I would like to contribute to carbon dioxyde reduction.</p>
        </div>
        <div class="card-footer">
          <a href="https://www.linkedin.com/in/janis-reboul-mtp/" class="btn linkedin-btn">LinkedIn</a>
          <a href="https://github.com/JanisReboul34" class="btn github-btn">GitHub</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

app/templates/home.html
{% extends "layout.html" %}
{% block content %}

<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='./styles/home.css') }}">
</head>

<main>
  <div class="hero-overlay">
    <h1>Carbon App</h1>
    <p>Calculate your carbon footprint and learn how to reduce it!</p>
    <a href="{{ url_for('calculator.page') }}" class="btn-solid">Get started</a>
  </div>
</main>

<div class="container">
  <section class="content">
    <h2>Why should you care?</h2>
    <br>
    <p>Climate change is one of the most pressing challenges of our time, with far-reaching impacts on 
        the environment, human health, and global economies. Rising temperatures, extreme weather events, and 
        biodiversity loss are just some of the consequences already affecting communities around the world. 
        But you have the power to make a difference. By taking responsibility for your carbon footprint, you can 
        play an active role in slowing down climate change. Small, everyday actions, like choosing sustainable transport, 
        reducing energy use, or eating more plant-based foods, can collectively lead to meaningful change. 
        When individuals, businesses, and governments work together toward climate solutions, we can build a 
        cleaner, healthier, and more sustainable future for everyone.</p>
    <br>
    <a href="{{ url_for('methodology.page') }}" class="btn custom-btn2"> Read more about our app!</a> 
    <a href="{{ url_for('about.page') }}" class="btn custom-btn2">Read more about our team!</a>
    
  </section>
</div>

{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{{url_for('static', filename='./styles/layout.css')}}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <title>Document</title>
</head>

<body>
    <div class="wrapper">
    <header class="sticky-top">
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid container">
                <a class="navbar-brand" href="{{url_for('home.page')}}">
                    <img src="{{url_for('static', filename='./images/logo.png')}}" alt="Logo" width="50" height="50"
                        class="d-inline-block align-text-middle">
                    <span>Carbon App</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    {% if current_user.is_authenticated %}
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('calculator.page')}}">Calculator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('calculator.your_data')}}">Your Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('methodology.page')}}">Methodology</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('about.page')}}">About Us</a>
                        </li>
                    </ul>  
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                          <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
                        </li>
                    </ul>
                    {% else %}
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('calculator.page')}}">Calculator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('methodology.page')}}">Methodology</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('about.page')}}">About Us</a>
                        </li>
                    </ul>  
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </nav>
    </header>
    
        {% block content %} {% endblock %}
        <div class="push"></div>
    </div>
        
    
    <footer>
        <h5><a href="#" >Take me to the TOP!</a></h5>

        <p>&copy; NHH 2025 - Team 3</p>
        
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/methodology.html
{% extends "layout.html" %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Carbon Footprint App</title>
    <link rel="stylesheet" href="{{url_for('static', filename='./styles/methodology.css')}}">
  </head>

    <h1>Our Methodology</h1>
    <a href="{{url_for('methodology.download')}}" class="btn-solid">Download our paper!</a><br>
    <div class="grid">
    
      <div class="box full-width">
        
        <h2>Understanding Carbon Footprints</h2>
        <p>How Do We Calculate Carbon Emissions?<br>
        Our approach to calculating carbon emissions involves considering various factors such as fuel type, distance traveled, and energy efficiency. We utilize established formulas that comply with Euro Emissions Standards to ensure accuracy and reliability. By inputting trip details such as distance, vehicle type, fuel type, and the number of passengers, users can calculate their emissions and compare different transport options like cars, bikes, and public transport.<br><br>
        We use this General Formula for each means of transport:<br>
        \( CO_2 = d * \frac{fe}{p} \)<br>
        \( fe =  \) Emission Factor in \( CO_2 / km \)<br>
        \( d =  \) Distance<br>
        \( p =  \) Amount of Passengers</p>
      </div>
  
      <div class="box">
        <h2>Cars</h2>
        <p>According to the Worldwide Harmonised Light Vehicles Test Procedures (WLTP) in 2019, CO2 emissions for cars by fuel type are the following:<br>
        Gasoline: 120 – 180 g/km<br>
        Diesel: 100 – 160 g/km<br>
        Hybrid (gasoline): 50 – 100 g/km<br>
        Electric: 26 g/km (tailpipe) - but depends on electricity generation<br>
        LPG / CNG: 100 - 130 g/km<br><br>
        Example to understand with a gasoline car:<br>
        If it consumes 6 L / 100 km, it emits approximately:<br><br>
        6 L × 2.3 kg CO₂/L = 13.8 kg CO₂ / 100 km<br>
        Or 138 g CO₂ / km<br>
        (Gasoline produces approximately 2.3 kg of CO₂ per litre burnt, diesel ~2.6 kg/L).</p>
      </div>
  
      <div class="box">
        <h2>Buses</h2>
        <p>According to a study of Chalmers tekniska högskola - Metodrapport för Klimatsmartsemester version 4.1 and NHO Transport:<br><br>
        Diesel bus: 30 g/km<br>
        Electric train in the Nordic Countries: 13 g/km</p>
      </div>
  
      <div class="box">
        <h2>Airplanes</h2>
        <p>The French agency of the ecological transition (ADEME) has calculated CO2 emissions for flights:<br>
        Domestic flights (less than 600 km): 250–300 g CO₂/km. Bergen-Oslo for example<br>
        Short hauls (600–3700 km): 150–200 g CO₂/km. Bergen-Paris for example<br>
        Long hauls (>3700 km): 90–130 g CO₂/km. Oslo-New York for example<br><br>
        It is important to note that these figures vary according to the type of aircraft, the load factor and the class of travel. For example, the business class can emit 2 to 3 times more than the economic class, because one seat occupies more space in the aircraft. For one row of seats, we can fit six seats of economic class and only two or three of business class. However, the plane needs the same amount of fuel to fly the same distance.</p>
      </div>
  
      <div class="box">
        <h2>Trains</h2>
        <p>In Norway, bus transportation is managed through a collaboration among several companies. We will incorporate data provided by Vy. Specifically, the emission factor for electric buses will be directly sourced from Vy's data.<br><br>
        Non-renewable energy:<br>
        Diesel: 27 g/km<br>
        Biodiesel: 14 g/km<br>
        Electric train in the Nordic countries: 13 g/km</p>
      </div>
  
      <div class="box">
        <h2>Motorbike & E-bike</h2>
        <p>Motorbike: engine size and emissions:<br>
        Electric scooter: 0 g/km (direct)<br>
        Small scooter (≤125cc) (Light city usage, efficient): 60–100 g/km<br>
        Medium motorcycle (125–500cc) (Urban + peri-urban use): 90–150 g/km<br>
        Large motorcycle (≥500cc) (Touring, highway bikes): 130–200+ g/km<br><br>
        A motorbike is generally a bit better than a car in CO₂/km, especially small scooters.<br>
        BUT! Motorbikes emit more of certain local air pollutants (like CO, HC, and NOx) than modern cars, especially older models or 2-stroke engines.</p>
      </div>
  
      <div class="box">
        <h2>Walking</h2>
        <p>Walking and using bikes produce zero emissions, making them the most environmentally friendly modes of transportation.</p>
      </div>

      <div class="full-width box">
        <h2>Euro Emissions Standards</h2>
        <p>Our calculations adhere to Euro Emissions Standards, which set strict limits on pollutant emissions from vehicles. These standards ensure that our estimates are accurate and comply with regulatory requirements, providing users with reliable data to make informed decisions about their transportation choices.</p>
      </div>
    </div>

{% endblock content %}