app/calculator/forms.py
from flask_wtf import FlaskForm
from wtforms import  SubmitField,  SelectField,  FloatField, IntegerField
from wtforms.validators import InputRequired

class Form(FlaskForm):
  method = SelectField("Method of Transport", [InputRequired()],
                       choices=[("Car", "Car"), ("Bus", "Bus"), ('Train', 'Train'), ("Plane", "Plane"), ("Ferry", "Ferry"), ("Motorbike", "Motorbike"), ("Scooter", "Scooter"), ("Bicycle", "Bicycle"), ("Walk", "Walk")])
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Petrol', 'Petrol'), ('Biodiesel', 'Biodiesel'), ('Hybrid (gasoline)', 'Hybrid (gasoline)'), ('No Fossil Fuel', 'No Fossil Fuel')])
  passengers = IntegerField("Number of Passengers", default=1)
  submit = SubmitField('Submit')

app/calculator/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, flash, jsonify
from app.models import Transport
from app import db
from datetime import timedelta, datetime
from flask_login import login_required, current_user
from app.calculator.forms import Form
import json

calculator=Blueprint('calculator',__name__)

#Emissions factor per transport in kg per passemger km
#Data from: http://efdb.apps.eea.europa.eu/?source=%7B%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%2C%22display_type%22%3A%22tabular%22%7D
efco2={'Bus':{'Diesel':0.03,'CNG':0.0285, 'No Fossil Fuel':0.013},
    'Car':{'Petrol':0.180,'Diesel':0.160, 'Hybrid (gasoline)': 0.100, 'CNG': 0.130, 'No Fossil Fuel':0.026},
    'Train': {'Diesel': 0.027, 'Biodiesel': 0.014, 'No Fossil Fuel': 0.013}, ##ADD BIODIESEL
    'Plane':{'Petrol':0.300},
    'Ferry':{'Diesel':0.019, 'CNG': 0.01425},
    'Motorbike':{'Petrol':0.200},
    'Scooter':{'Petrol': 0.100,'No Fossil Fuel':0},
    'Bicycle':{'No Fossil Fuel':0},
    'Walk':{'No Fossil Fuel':0}}


#Calculator, main page
@calculator.route('/calculator', methods=['GET','POST'])
@login_required
def page():
    form = Form()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = form.method.data
        passengers = form.passengers.data
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * (efco2[transport][fuel]/passengers)

        co2 = float("{:.2f}".format(co2))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('calculator.your_data'))
    return render_template('calculator/calculator.html', title='New entry', form=form)

@calculator.route('/get-items')
def get_items():
    method = request.args.get('method')
    items_dict = {
        'Bus': ['Diesel', 'CNG', 'No Fossil Fuel'],
        'Car': ['Petrol', 'Diesel', 'Hybrid (gasoline)', 'CNG', 'No Fossil Fuel'],
        'Train': ['Diesel', 'Biodiesel', 'No Fossil Fuel'],
        'Plane': ['Petrol'],
        'Ferry': ['Diesel', 'CNG'],
        'Motorbike': ['Petrol'],
        'Scooter': ['Petrol', 'No Fossil Fuel'],
        'Bicycle': ['No Fossil Fuel'],
        'Walk': ['No Fossil Fuel']
    }
    items = items_dict.get(method, [])
    return jsonify({'items': items})


#Your data
@calculator.route('/calculator/your_data')
@login_required
def your_data():
    #Table
    entries = Transport.query.filter_by(author=current_user). \
        filter(Transport.date> (datetime.now() - timedelta(days=30))).\
        order_by(Transport.date.desc()).order_by(Transport.transport.asc()).all()

#Emissions by category
    emissions_by_transport = db.session.query(db.func.sum(Transport.co2), Transport.transport). \
        filter(Transport.date > (datetime.now() - timedelta(days=30))).filter_by(author=current_user). \
        group_by(Transport.transport).order_by(Transport.transport.asc()).all()
    emission_transport = [0, 0, 0, 0, 0, 0, 0, 0, 0]
    first_tuple_elements = []
    second_tuple_elements = []
    for a_tuple in emissions_by_transport:
        first_tuple_elements.append(a_tuple[0])
        second_tuple_elements.append(a_tuple[1])

    if 'Bus' in second_tuple_elements:
        index_bus = second_tuple_elements.index('Bus')
        emission_transport[1]=first_tuple_elements[index_bus]
    else:
        emission_transport[1]

    if 'Car' in second_tuple_elements:
        index_car = second_tuple_elements.index('Car')
        emission_transport[2]=first_tuple_elements[index_car]
    else:
        emission_transport[2]

    if 'Ferry' in second_tuple_elements:
        index_ferry = second_tuple_elements.index('Ferry')
        emission_transport[3]=first_tuple_elements[index_ferry]
    else:
        emission_transport[3]

    if 'Motorbike' in second_tuple_elements:
        index_motorbike = second_tuple_elements.index('Motorbike')
        emission_transport[4]=first_tuple_elements[index_motorbike]
    else:
        emission_transport[4]

    if 'Plane' in second_tuple_elements:
        index_plane = second_tuple_elements.index('Plane')
        emission_transport[5]=first_tuple_elements[index_plane]
    else:
        emission_transport[5]
    
    if 'Scooter' in second_tuple_elements:
        index_scooter = second_tuple_elements.index('Scooter')
        emission_transport[6]=first_tuple_elements[index_scooter]
    else:
        emission_transport[6]

    if 'Train' in second_tuple_elements:
        index_train = second_tuple_elements.index('Train')
        emission_transport[7]=first_tuple_elements[index_train]
    else:
        emission_transport[7]

    #Kilometers by category
    kms_by_transport = db.session.query(db.func.sum(Transport.kms), Transport.transport). \
        filter(Transport.date > (datetime.now() - timedelta(days=30))).filter_by(author=current_user). \
        group_by(Transport.transport).order_by(Transport.transport.asc()).all()
    kms_transport = [0, 0, 0, 0, 0, 0, 0, 0, 0]
    first_tuple_elements = []
    second_tuple_elements = []
    for a_tuple in kms_by_transport:
        first_tuple_elements.append(a_tuple[0])
        second_tuple_elements.append(a_tuple[1])

    if 'Bicycle' in second_tuple_elements:
        index_bicycle = second_tuple_elements.index('Bicycle')
        kms_transport[0]=first_tuple_elements[index_bicycle]
    else:
        kms_transport[0] 

    if 'Bus' in second_tuple_elements:
        index_bus = second_tuple_elements.index('Bus')
        kms_transport[1]=first_tuple_elements[index_bus]
    else:
        kms_transport[1]

    if 'Car' in second_tuple_elements:
        index_car = second_tuple_elements.index('Car')
        kms_transport[2]=first_tuple_elements[index_car]
    else:
        kms_transport[2]

    if 'Ferry' in second_tuple_elements:
        index_ferry = second_tuple_elements.index('Ferry')
        kms_transport[3]=first_tuple_elements[index_ferry]
    else:
        kms_transport[3]

    if 'Motorbike' in second_tuple_elements:
        index_motorbike = second_tuple_elements.index('Motorbike')
        kms_transport[4]=first_tuple_elements[index_motorbike]
    else:
        kms_transport[4]

    if 'Plane' in second_tuple_elements:
        index_plane = second_tuple_elements.index('Plane')
        kms_transport[5]=first_tuple_elements[index_plane]
    else:
        kms_transport[5]

    if 'Scooter' in second_tuple_elements:
        index_scooter = second_tuple_elements.index('Scooter')
        kms_transport[6]=first_tuple_elements[index_scooter]
    else:
        kms_transport[6]   

    if 'Train' in second_tuple_elements:
        index_train = second_tuple_elements.index('Train')
        kms_transport[7]=first_tuple_elements[index_train]
    else:
        kms_transport[7]   

    if 'Walk' in second_tuple_elements:
        index_walk = second_tuple_elements.index('Walk')
        kms_transport[8]=first_tuple_elements[index_walk]
    else:
        kms_transport[8]    

    #Emissions by date (individual)
    emissions_by_date = db.session.query(db.func.sum(Transport.co2), Transport.date). \
        filter(Transport.date > (datetime.now() - timedelta(days=30))).filter_by(author=current_user). \
        group_by(Transport.date).order_by(Transport.date.asc()).all()
    over_time_emissions = []
    dates_label = []
    for total, date in emissions_by_date:
        dates_label.append(date.strftime("%m-%d-%y"))
        over_time_emissions.append(total)    

    #Kms by date (individual)
    kms_by_date = db.session.query(db.func.sum(Transport.kms), Transport.date). \
        filter(Transport.date > (datetime.now() - timedelta(days=30))).filter_by(author=current_user). \
        group_by(Transport.date).order_by(Transport.date.asc()).all()
    over_time_kms = []
    dates_label = []
    for total, date in kms_by_date:
        dates_label.append(date.strftime("%m-%d-%y"))
        over_time_kms.append(total)      


    return render_template('calculator/your_data.html', title='Your Data', entries=entries,
        emissions_by_transport_python_dic=emissions_by_transport,     
        emission_transport_python_list=emission_transport,             
        emissions_by_transport=json.dumps(emission_transport),
        kms_by_transport=json.dumps(kms_transport),
        over_time_emissions=json.dumps(over_time_emissions),
        over_time_kms=json.dumps(over_time_kms),
        dates_label=json.dumps(dates_label))
    

#Delete emission
@calculator.route('/calculator/delete-emission/<int:entry_id>')
def delete_emission(entry_id):
    entry = Transport.query.get_or_404(int(entry_id))
    db.session.delete(entry)
    db.session.commit()
    flash("Entry deleted", "success")
    return redirect(url_for('calculator.your_data'))
    
  

app/methodology/routes.py
from flask import render_template, Blueprint, send_file
methodology = Blueprint('methodology', __name__)

@methodology.route('/methodology')
def page():
  return render_template('methodology.html')

@methodology.route('/downloadPaper')
def download ():
    path = "./static/downloadable/Carbon-App-Paper-Group-3-2025.pdf"
    return send_file(path, as_attachment=True)

app/templates/calculator/calculator.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->

<Head>
  <link rel="stylesheet" href="{{url_for('static', filename='./styles/calculator.css')}}">
  <script type="text/javascript" src="{{url_for('static', filename='./js/fieldChanger.js')}}"></script>
</Head>

<section class="section_header_calculator">
  <div class="container">

    <div class="header_calculator">
      <div class="box">
        <img src="{{url_for('static', filename='images/Logo_calculator.webp')}}" alt="Logo" />
      </div>
      <div class="box">
        <h1><span class="text-logo"> Carbon App Calculator</span></h1>
        <p style="text-align:left;">
          Welcome to your carbon emission calculator.
        </p>  
        <p style="text-align: left">
          Please choose your mode of transportation from the seven categories below and enter the number of kilometers to travel.
          By doing so, you can compare your emissions with other means of transport and see if you have reduced your carbon footprint. If not, you'll know what to do next time!
        </p>
        <div class="container_buttons_links_header_calculator">
          <div class="btn">
            <a href="{{url_for('methodology.page')}}" class="btn-solid">Methodology</a>
          </div>
          <div class="btn">
            <a href="{{url_for('calculator.your_data')}}" class="btn-solid">Your data</a>
          </div>
        </div>
      </div>
      
    </div>

  </div>
</section>

<!-- calculator_new_entry_main -->
<section class="section_calculator_new_entry_main">
  <div class="container">

    <section class="new_entry">
      <div class="container">
        <div class="box">

        </div>
        <div class="box">
          <div class="h1 mb-3" style="text-align: center; color:  #568c63;">
            <h3>Please, select your mean of conveyance in the boxes below</h3>
            <i class="fa-solid fa-leaf"></i>
          </div>
          <p class="centered">
            Please, fill in these sections:
          </p>
          <form method="POST" action="">
            {{ form.csrf_token }}
            <fieldset class="form-group">

              <div class="form-group">
                {{ form.method.label(class="form-control-label") }}
                {% if form.method.errors %}
                {{ form.method(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.method.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.method(class="form-control form-control-lg") }}
                {% endif %}
              </div>

              <div class="form-group">
                {{ form.kms.label(class="form-control-label") }}
                {% if form.kms.errors %}
                {{ form.kms(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.kms.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.kms(class="form-control form-control-lg") }}
                {% endif %}
              </div>

              <div class="form-group">
                {{ form.fuel_type.label(class="form-control-label") }}
                {% if form.fuel_type.errors %}
                    {{ form.fuel_type(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.fuel_type.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.fuel_type(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group" id="passenger-select">
              {{ form.passengers.label(class="form-control-label") }}
              {% if form.passengers.errors %}
                  {{ form.passengers(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.passengers.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.passengers(class="form-control form-control-lg") }}
              {% endif %}
          </div>

            </fieldset>
            </br>
            <div class="form-group">
              {{ form.submit(class="btn_calculator_new_entry_main") }}
            </div>
          </form>
        </div>
        <div class="box">

        </div>
      </div>
    </section>

  </div>
</section>

{% endblock content %}


app/templates/calculator/your_data.html
{% extends "layout.html" %}
{% block content %}

<Head>
    <link rel="stylesheet" href="{{url_for('static', filename='./styles/calculator.css')}}">
</Head>

    <!-- New Entry Section -->
    <section class="main_menu">
      <div class="container">
          <div class="box">

          </div>
          <div class="box"> 
              <div class="container_buttons_links_main_menu">
                  <div class="btn">
                      <a href="{{ url_for('calculator.page') }}" class="btn_calculator_new_entry_main">New Entry</a>
                  </div>   
              </div>        
          </div>
          <div class="box">

          </div>
      </div>
    </section> 

    <!-- Table Section -->
    <section class="table_main">
        <div class="container">
            <h1>Your Data</h1>
        </div>
    </section> 
 
    <!-- Two Emissions Graph Section -->
    <section class="two_emissions_graphs">
        <div class="container">
            <div class="box">
                    <canvas id="emissions_by_transport"></canvas>
            </div>
            <div class="box">
                <canvas id="over_time_emissions"></canvas> 
            </div>
        </div>
    </section> 

    <!-- Two Emissions Graph Section -->
    <section class="two_emissions_graphs">
        <div class="container">
            <div class="box">
                <canvas id="kms_by_transport"></canvas>
            </div>
            <div class="box">
                <canvas id="over_time_kms"></canvas>
            </div>
        </div>
    </section> 

    <!-- Table Section -->
    <section class="table_main">
    <div class="container table-responsive">
        <div class="box">

        </div>
        <div class="box">  
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div> 
                    {% endfor %}
                {% endif %}
            {% endwith %}         
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">User</th>
                        <th scope="col">Date</th>
                        <th scope="col">Kilometres</th>
                        <th scope="col">Transport</th>
                        <th scope="col">Fuel</th>
                        <th scope="col">Co2</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for entry in entries %}
                        <tr>
                            <th scope="row">{{ current_user.username }}</th>
                            <td>{{ entry.date.strftime("%m-%d-%Y") }}</td>
                            <td>{{ entry.kms }}</td>
                            <td>{{ entry.transport }}</td>
                            <td>{{ entry.fuel }}</td>
                            <td>{{ entry.co2 }}</td>
                            <td><a href="{{ url_for('calculator.delete_emission', entry_id = entry.id) }}" class="btn btn-outline-danger btn-sm">Delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>       
        </div>
        <div class="box">

        </div>
    </div>
    </section> 


    {% block javascript %}
    <script>
        // Emissions
        let emission_transport_data = JSON.parse({{ emissions_by_transport | tojson }})    
        Chart.scaleService.updateScaleDefaults('linear', {
                ticks: {
                    min: 0
                }
        });
        console.log(emission_transport_data)
    
    
        let emissions_by_transport_chart = new Chart(emissions_by_transport, {
                type: 'pie',
                data: {
                labels: ['Bicycle', 'Bus', 'Car', 'Ferry', 'Motorbike', 'Plane', 'Scooter', 'Train', 'Walk'],
                    datasets: [{
                        data: emission_transport_data,
                        backgroundColor: ['#9ac2be', '#f2e3b6', '#f2c299',
                            '#f2935c', '#5fd9cd', '#f2d95c', '#f2b84b', '#f27979', '#8F00FF' ],
    
                        borderWidth: 1,
                        hoverBorderColor: "black",
                        hoverBorderWidth: 2,
                        hoverBackgroundColor: 'rgba(154, 245, 140)',
                        pointHoverRadius: 5
                    }],
                },
                options: {
                        title: {
                            display: true,
                                text: "Emissions by type of transport (30 last days)",
                                    fontColor: "black",
                                    fontSize: 20,
                        },
                        legend: {
                            position: "right",
                                labels: {
                                fontColor: "black"
                            },
                            display: true,
                        },
    
                        elements: {
                            hitRadius: 3,
                        },
                        responsive: true,
                        maintainAspectRatio: false,
                }
            })

        over_time_emissions = JSON.parse({{over_time_emissions | tojson}})
        labels = JSON.parse({{ dates_label  | tojson}})

        new Chart(document.getElementById("over_time_emissions"), {
                type: "line",
                data:
                {
                    labels: labels,
                    datasets: [
                        {
                        label: "Individual Emissions (30 past days)",                           
                        data: over_time_emissions,
                        fill: false,
                        borderColor: '#5fd9cd',
                        lineTension: 0.1
                        }
                ]
                },                    
                options: {responsive: true,
                    maintainAspectRatio: false,}
            });  
            
        // Kilometers
        let kms_transport_data = JSON.parse({{ kms_by_transport | tojson }})    
        Chart.scaleService.updateScaleDefaults('linear', {
                ticks: {
                    min: 0
                }
        });
        let kms_by_transport_chart = new Chart(kms_by_transport, {
                type: 'pie',
                data: {
                labels: ['Bicycle', 'Bus', 'Car', 'Ferry', 'Motorbike', 'Plane', 'Scooter', 'Train', 'Walk'],
                    datasets: [{
                        label: "Income Vs Expenses",
                        data: kms_transport_data,
                        backgroundColor: ['#9ac2be', '#f2e3b6', '#f2c299',
                            '#f2935c', '#5fd9cd', '#f2d95c', '#f2b84b', '#f27979', '#8F00FF' ],    
                        borderWidth: 1,
                        hoverBorderColor: "black",
                        hoverBorderWidth: 2,
                        hoverBackgroundColor: 'rgba(154, 245, 140)',
                        pointHoverRadius: 5
                    }],
                },
                options: {
                        title: {
                            display: true,
                                text: "Kilometers by type of transport (30 last days)",
                                fontColor: "black",
                                fontSize: 20,
                        },
                        legend: {
                            position: "right",
                                labels: {
                                fontColor: "black"
                            },
                            display: true,
                        },
    
                        elements: {
                            hitRadius: 3,
                        },
                        responsive: true,
                        maintainAspectRatio: false,
                }
            })
            
        over_time_kms = JSON.parse({{over_time_kms | tojson}})
        labels = JSON.parse({{ dates_label  | tojson}})

        new Chart(document.getElementById("over_time_kms"), {
                type: "line",
                data:
                {
                    labels: labels,
                    datasets: [
                        {
                        label: "Individual Kilometers (30 past days)",                            
                        data: over_time_kms,
                        fill: false,
                        borderColor: '#f2d95c',
                        lineTension: 0.1
                        }
                ]
                },                    
                options: {responsive: true,
                    maintainAspectRatio: false,}
            });   

        </script>
    {% endblock%}        
{% endblock content %}